spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password:
  flyway:
    user: postgres
    password:
    url: jdbc:postgresql://localhost:5432/spring_reactive